import React, { useState, useEffect, useRef } from 'react';
import { Topbar } from '../App';
import { getCases } from '../lib/api';
import SignatureCanvas from 'react-signature-canvas';
import { FileText, FileDown, Download, PenTool, BarChart3, Settings2, FileImage, LayoutTemplate } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun } from 'docx';
import * as XLSX from 'xlsx';
import html2canvas from 'html2canvas';

export default function Reporting({ currentUser }: { currentUser: any }) {
  const [cases, setCases] = useState<any[]>([]);
  const [selectedCase, setSelectedCase] = useState<string>('');
  const [template, setTemplate] = useState<string>('case_summary');
  const [reportTitle, setReportTitle] = useState('Official Case Report');
  const [notes, setNotes] = useState('');
  
  const [signatureData, setSignatureData] = useState<string | null>(null);
  const sigCanvas = useRef<SignatureCanvas>(null);
  const reportRef = useRef<HTMLDivElement>(null);
  const chartRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    getCases().then(setCases);
  }, []);

  const clearSignature = () => {
    sigCanvas.current?.clear();
    setSignatureData(null);
  };

  const saveSignature = () => {
    if (sigCanvas.current && !sigCanvas.current.isEmpty()) {
      setSignatureData(sigCanvas.current.getTrimmedCanvas().toDataURL('image/png'));
    }
  };

  // Mock data for charts if a case is selected
  const chartData = [
    { name: 'Evidence Items', count: Math.floor(Math.random() * 20) + 5 },
    { name: 'Interviews', count: Math.floor(Math.random() * 10) + 2 },
    { name: 'Locations', count: Math.floor(Math.random() * 5) + 1 },
    { name: 'Suspects', count: Math.floor(Math.random() * 3) + 1 },
  ];

  const exportPDF = async () => {
    const pdf = new jsPDF('p', 'pt', 'a4');
    let yPos = 40;

    pdf.setFontSize(20);
    pdf.text(reportTitle, 40, yPos);
    yPos += 30;

    pdf.setFontSize(12);
    pdf.text(`Generated by: ${currentUser?.name || 'Unknown Officer'}`, 40, yPos);
    yPos += 20;
    
    const activeCase = cases.find(c => c.id === selectedCase);
    if (activeCase) {
      pdf.text(`Case Title: ${activeCase.title}`, 40, yPos);
      yPos += 20;
      pdf.text(`Status: ${activeCase.status} | Priority: ${activeCase.priority}`, 40, yPos);
      yPos += 30;
    }

    if (notes) {
      pdf.text('Officer Notes:', 40, yPos);
      yPos += 20;
      const splitNotes = pdf.splitTextToSize(notes, 500);
      pdf.text(splitNotes, 40, yPos);
      yPos += (splitNotes.length * 15) + 20;
    }

    // Chart
    if (chartRef.current) {
      const canvas = await html2canvas(chartRef.current);
      const imgData = canvas.toDataURL('image/png');
      pdf.text('Statistical Analysis:', 40, yPos);
      yPos += 20;
      // scale image to fit width (max 500)
      const imgWidth = 500;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      if (yPos + imgHeight > 800) {
        pdf.addPage();
        yPos = 40;
      }
      
      pdf.addImage(imgData, 'PNG', 40, yPos, imgWidth, imgHeight);
      yPos += imgHeight + 30;
    }

    // Table
    autoTable(pdf, {
      startY: yPos,
      head: [['Metric', 'Count']],
      body: chartData.map(d => [d.name, d.count]),
    });
    
    yPos = (pdf as any).lastAutoTable.finalY + 40;

    if (signatureData) {
      if (yPos + 100 > 800) {
        pdf.addPage();
        yPos = 40;
      }
      pdf.text('Authorized Signature:', 40, yPos);
      pdf.addImage(signatureData, 'PNG', 40, yPos + 10, 150, 50);
      pdf.text('_______________________', 40, yPos + 75);
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, 40, yPos + 90);
    }

    pdf.save(`${reportTitle.replace(/\s+/g, '_').toLowerCase()}.pdf`);
  };

  const exportWord = async () => {
    const children: any[] = [
      new Paragraph({ text: reportTitle, heading: HeadingLevel.HEADING_1 }),
      new Paragraph({ text: `Generated by: ${currentUser?.name || 'Unknown Officer'}` }),
      new Paragraph({ text: `Date: ${new Date().toLocaleDateString()}` }),
      new Paragraph({ text: "" })
    ];

    const activeCase = cases.find(c => c.id === selectedCase);
    if (activeCase) {
      children.push(new Paragraph({ text: `Case Title: ${activeCase.title}`, heading: HeadingLevel.HEADING_2 }));
      children.push(new Paragraph({ text: `Status: ${activeCase.status} | Priority: ${activeCase.priority}` }));
      children.push(new Paragraph({ text: "" }));
    }

    if (notes) {
      children.push(new Paragraph({ text: "Officer Notes:", heading: HeadingLevel.HEADING_3 }));
      children.push(new Paragraph({ text: notes }));
      children.push(new Paragraph({ text: "" }));
    }
    
    children.push(new Paragraph({ text: "Statistical Data:", heading: HeadingLevel.HEADING_3 }));
    chartData.forEach(d => {
      children.push(new Paragraph({ text: `${d.name}: ${d.count}` }));
    });
    children.push(new Paragraph({ text: "" }));

    if (signatureData) {
      children.push(new Paragraph({ text: "Authorized Signature:", heading: HeadingLevel.HEADING_3 }));
      // We cannot easily embed base64 image in docx without arraybuffer conversion. 
      // For simplicity in client side, we'll just add a placeholder if image conversion is complex,
      // but docx ImageRun supports Uint8Array. We can convert base64 to Uint8Array.
      const base64Data = signatureData.replace(/^data:image\/png;base64,/, "");
      const binaryString = window.atob(base64Data);
      const len = binaryString.length;
      const bytes = new Uint8Array(len);
      for (let i = 0; i < len; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      
      children.push(new Paragraph({
        children: [
          new ImageRun({
            data: bytes,
            transformation: { width: 150, height: 50 },
            type: 'png'
          })
        ]
      }));
      children.push(new Paragraph({ text: '_______________________' }));
    }

    const doc = new Document({
      sections: [{ properties: {}, children }]
    });

    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${reportTitle.replace(/\s+/g, '_').toLowerCase()}.docx`;
    a.click();
  };

  const exportExcel = () => {
    const workbook = XLSX.utils.book_new();
    
    // Summary Sheet
    const summaryData = [
      ['Report Title', reportTitle],
      ['Generated By', currentUser?.name || 'Unknown Officer'],
      ['Date', new Date().toLocaleDateString()],
      ['Notes', notes]
    ];
    const activeCase = cases.find(c => c.id === selectedCase);
    if (activeCase) {
      summaryData.push(['Case Title', activeCase.title]);
      summaryData.push(['Status', activeCase.status]);
      summaryData.push(['Priority', activeCase.priority]);
    }
    
    const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(workbook, wsSummary, "Summary");
    
    // Data Sheet
    const wsData = XLSX.utils.json_to_sheet(chartData);
    XLSX.utils.book_append_sheet(workbook, wsData, "Metrics");
    
    XLSX.writeFile(workbook, `${reportTitle.replace(/\s+/g, '_').toLowerCase()}.xlsx`);
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-hidden bg-slate-950">
      <Topbar title="Advanced Reporting & Export" />
      
      <div className="flex flex-1 overflow-hidden">
        {/* Settings Sidebar */}
        <div className="w-80 border-r border-slate-800 bg-slate-900 p-6 flex flex-col gap-6 overflow-y-auto shrink-0">
          <div>
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <LayoutTemplate className="w-5 h-5 text-blue-500" /> Report Configuration
            </h2>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Report Title</label>
                <input 
                  type="text" 
                  value={reportTitle}
                  onChange={e => setReportTitle(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 focus:outline-none focus:border-blue-500 text-sm text-slate-200"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Template Type</label>
                <select 
                  value={template}
                  onChange={e => setTemplate(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 focus:outline-none focus:border-blue-500 text-sm text-slate-200"
                >
                  <option value="case_summary">Case Summary Report</option>
                  <option value="evidence_log">Evidence Log</option>
                  <option value="blank">Custom / Blank</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Target Case (Optional)</label>
                <select 
                  value={selectedCase}
                  onChange={e => setSelectedCase(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 focus:outline-none focus:border-blue-500 text-sm text-slate-200"
                >
                  <option value="">-- Select Case --</option>
                  {cases.map(c => (
                    <option key={c.id} value={c.id}>{c.title} ({c.status})</option>
                  ))}
                </select>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Additional Notes</label>
                <textarea 
                  value={notes}
                  onChange={e => setNotes(e.target.value)}
                  rows={4}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2 focus:outline-none focus:border-blue-500 text-sm text-slate-200 resize-none"
                  placeholder="Enter officer notes or summary..."
                />
              </div>
            </div>
          </div>
          
          <div className="border-t border-slate-800 pt-6">
            <h2 className="text-sm font-bold mb-4 flex items-center gap-2 text-slate-300">
              <PenTool className="w-4 h-4 text-emerald-500" /> Digital Signature
            </h2>
            <div className="bg-slate-200 rounded-xl overflow-hidden mb-2 border-2 border-slate-700">
              <SignatureCanvas 
                ref={sigCanvas}
                penColor="black"
                canvasProps={{width: 270, height: 100, className: 'sigCanvas'}}
                onEnd={saveSignature}
              />
            </div>
            <div className="flex gap-2">
              <button onClick={clearSignature} className="flex-1 bg-slate-800 hover:bg-slate-700 text-xs py-2 rounded-lg transition-colors font-medium">Clear</button>
            </div>
          </div>

        </div>

        {/* Preview & Export */}
        <div className="flex-1 flex flex-col bg-slate-950">
          <div className="p-4 border-b border-slate-800 bg-slate-900 flex justify-between items-center shrink-0">
            <h2 className="font-bold flex items-center gap-2">
              <FileImage className="w-5 h-5 text-indigo-500" /> Report Preview
            </h2>
            
            <div className="flex gap-2">
              <button onClick={exportPDF} className="flex items-center gap-2 bg-rose-600/20 hover:bg-rose-600/30 text-rose-400 px-4 py-2 rounded-lg transition-colors font-medium text-sm">
                <FileDown className="w-4 h-4" /> PDF
              </button>
              <button onClick={exportWord} className="flex items-center gap-2 bg-blue-600/20 hover:bg-blue-600/30 text-blue-400 px-4 py-2 rounded-lg transition-colors font-medium text-sm">
                <FileText className="w-4 h-4" /> Word
              </button>
              <button onClick={exportExcel} className="flex items-center gap-2 bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-400 px-4 py-2 rounded-lg transition-colors font-medium text-sm">
                <BarChart3 className="w-4 h-4" /> Excel
              </button>
            </div>
          </div>
          
          {/* Live Preview Area */}
          <div className="flex-1 overflow-y-auto p-8">
            <div ref={reportRef} className="max-w-3xl mx-auto bg-white text-black p-10 rounded-lg shadow-2xl min-h-[800px]">
              
              <div className="border-b-2 border-slate-200 pb-6 mb-6 flex justify-between items-start">
                <div>
                  <h1 className="text-3xl font-serif font-bold text-slate-800">{reportTitle}</h1>
                  <p className="text-slate-500 mt-2">Generated by: {currentUser?.name || 'Officer'}</p>
                  <p className="text-slate-500">Date: {new Date().toLocaleDateString()}</p>
                </div>
                <div className="text-right">
                  <h2 className="font-bold text-slate-700 uppercase tracking-widest text-sm">Law Enforcement</h2>
                  <p className="text-slate-500 text-sm">Internal Records System</p>
                </div>
              </div>
              
              {selectedCase && (() => {
                const activeCase = cases.find(c => c.id === selectedCase);
                if (activeCase) return (
                  <div className="bg-slate-50 p-4 rounded-lg mb-6 border border-slate-200">
                    <h3 className="font-bold text-lg mb-2">Case Details</h3>
                    <p><strong>Title:</strong> {activeCase.title}</p>
                    <p><strong>Status:</strong> <span className="uppercase">{activeCase.status}</span></p>
                    <p><strong>Priority:</strong> <span className="uppercase">{activeCase.priority}</span></p>
                  </div>
                );
                return null;
              })()}
              
              {notes && (
                <div className="mb-8">
                  <h3 className="font-bold text-lg mb-2 border-b border-slate-200 pb-2">Officer Notes / Summary</h3>
                  <p className="whitespace-pre-wrap text-slate-700 leading-relaxed">{notes}</p>
                </div>
              )}
              
              <div className="mb-8">
                <h3 className="font-bold text-lg mb-4 border-b border-slate-200 pb-2">Statistical Data</h3>
                <div ref={chartRef} className="h-64 w-full bg-white">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={chartData}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="name" />
                      <YAxis />
                      <Tooltip />
                      <Bar dataKey="count" fill="#4f46e5" />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
              
              <div className="mt-16 pt-8 border-t-2 border-slate-200 flex justify-end">
                <div className="w-64 text-center">
                  <p className="text-sm text-slate-500 mb-2">Authorized Signature</p>
                  {signatureData ? (
                    <img src={signatureData} alt="Signature" className="h-16 mx-auto mb-2 mix-blend-multiply" />
                  ) : (
                    <div className="h-16 mb-2"></div>
                  )}
                  <div className="border-t border-slate-400"></div>
                  <p className="text-sm mt-2">{currentUser?.name || 'Officer Name'}</p>
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
